In [1]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [2]:
X,y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [4]:
X

array([[ 2.31039406,  0.96191555],
       [-0.71691921,  0.22918447],
       [ 0.76235513, -0.25301991],
       [ 2.12058097,  0.04027454],
       [-0.94661553,  0.29794505],
       [ 1.58550539, -1.0935131 ],
       [-0.22509656, -2.05661092],
       [-1.26671306, -1.90896636],
       [ 0.84832483, -0.67832131],
       [ 0.74516413,  0.68310528],
       [ 2.12281632,  0.19540939],
       [ 2.18535114, -1.14204897],
       [-0.71435281, -0.66860037],
       [ 1.19542951,  0.21231364],
       [ 0.32008912, -0.62051238],
       [-1.41855911, -0.59529107],
       [-1.10729158,  0.02290064],
       [-0.30606704,  0.68114487],
       [ 1.38037214,  0.6442377 ],
       [ 0.09996057, -0.52572252],
       [-1.12777341,  0.41886984],
       [-0.70803523,  0.93610877],
       [-1.40564771, -2.54492123],
       [ 1.76438171, -1.7338494 ],
       [ 1.11968565,  0.86677094],
       [-3.03041434, -2.27225141],
       [-0.80676584, -1.36556243],
       [ 0.45550706, -0.45735523],
       [ 0.25837334,

In [5]:
y

array([  71.92467428,   -8.55481664,    6.29163425,  113.58004792,
       -115.85136345,  -96.09593306, -130.45071438, -166.44875088,
          7.28637053,   96.77879264,   33.23442758, -132.06720073,
        -57.63964422,   40.85416021,   -8.30411607,   28.4195274 ,
        -38.87995514,  -28.5030261 ,   64.62317759,  -47.90020867,
         -2.5536664 ,   70.47424232, -127.85042541, -182.87420722,
        121.94267969, -230.5262195 , -120.10046148,   -3.24837831,
         22.64369138,  -15.24236951,  -84.31996242,   67.70424451,
         38.44166171,  -83.74433636,   26.3396505 ,   44.2501989 ,
        145.59884197,  139.94361106,  -58.62871039, -143.42242613,
        -30.79849587,   64.29985908,   49.07152469, -106.96774302,
         32.96802618,   78.46609524,   26.09828793,  -66.68916368,
         54.00499389,   98.59851362,   43.35154688,  121.86426412,
       -100.96857556,   72.0037077 ,  -50.06082516,  119.82678949,
          2.35656537,  126.58459116,  191.91491868,  -59.22199

In [6]:
df = pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})

In [7]:
df.shape

(100, 3)

In [8]:
df.head()

feature1  feature2      target
0  2.310394  0.961916   71.924674
1 -0.716919  0.229184   -8.554817
2  0.762355 -0.253020    6.291634
3  2.120581  0.040275  113.580048
4 -0.946616  0.297945 -115.851363

In [9]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.show()

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=3)

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
lr = LinearRegression()

In [13]:
lr.fit(X_train,y_train)

LinearRegression()

In [14]:
y_pred = lr.predict(X_test)
y_pred

array([-172.98339822,  109.1130278 , -136.36438602,   19.66388167,
         -4.30974152,   40.77692673,   93.77277111,   75.10877344,
       -167.68818958,  -40.46424192,  -23.7887916 ,   61.90743651,
         53.41138294,   34.11165672,   50.16506112,  -31.72313954,
        -67.39396758, -102.20580986,   -7.74026216,  127.60386263])

In [16]:
y_test

array([-103.12140763,  100.51236299, -130.45071438,   34.00345439,
        -59.95024725,   16.93860364,  128.26637825,   49.07152469,
       -230.5262195 ,   28.4195274 ,   31.31244284,   96.77879264,
         -9.07222986,  -69.47591087,   26.3396505 ,  -74.45619792,
        -23.59725055, -182.87420722,  -59.22199129,   78.46609524])

In [18]:
print("MAE:",mean_absolute_error(y_test,y_pred))
print("MSE:",mean_squared_error(y_test,y_pred))
print("R2-score:",r2_score(y_test,y_pred))

MAE: 45.90671172926705
MSE: 2709.583693531614
R2-score: 0.6895193860571215


In [76]:
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)
xGrid, yGrid = np.meshgrid(y, x)

z_final = lr.predict(final).reshape(10,10)

z = z_final

final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T

In [77]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.add_trace(go.Surface(x = x, y = y, z =z ))

fig.show()

In [ ]:
lr.coef_

array([59.64518074, 13.20409431])

In [ ]:
lr.intercept_

-7.55491251398082