In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/heart-disease-prediction-uci/heart.csv
/kaggle/input/mnist-digit-recognizer/train.csv
/kaggle/input/iris/Iris.csv
/kaggle/input/iris/database.sqlite


In [2]:
df = pd.read_csv('/kaggle/input/heart-disease-prediction-uci/heart.csv')

In [3]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [6]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [7]:
# Trainig above both model on same data

clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [8]:
# Prediction of both model using X_test

y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

### Accuracy : The percentage of instances that are correctly classified.

In [9]:
from sklearn.metrics import accuracy_score,confusion_matrix

print("Accuracy of Logistic Regression:",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees:",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression: 0.9016393442622951
Accuracy of Decision Trees: 0.8688524590163934


### Confusion Matrix

In [10]:
confusion_matrix(y_test,y_pred1)

array([[26,  6],
       [ 0, 29]])

#### confusion matrix for multi-classification problem

In [11]:
df1 = pd.read_csv('/kaggle/input/iris/Iris.csv')
df1.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [12]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df1['Species'] = encoder.fit_transform(df1['Species'])
df1.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [13]:
from sklearn.model_selection import train_test_split
X_train1,X_test1,y_train1,y_test1 = train_test_split(df1.iloc[:,0:-1],df1.iloc[:,-1],test_size=0.2,random_state=1)

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [15]:
clf3 = LogisticRegression()
clf4 = DecisionTreeClassifier()

In [16]:
clf3.fit(X_train1,y_train1)
clf4.fit(X_train1,y_train1)

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [17]:
y_pred3 = clf3.predict(X_test1)
y_pred4 = clf4.predict(X_test1)

In [18]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression:",accuracy_score(y_test1,y_pred3))
print("Accuracy of Decision Trees:",accuracy_score(y_test1,y_pred4))

Accuracy of Logistic Regression: 1.0
Accuracy of Decision Trees: 0.9666666666666667


In [19]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test1,y_pred3),columns=list(range(0,3)))

Logistic Regression Confusion Matrix



0   1  2
0  11   0  0
1   0  13  0
2   0   0  6

In [20]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test1,y_pred4),columns=list(range(0,3)))

Decision Tree Confusion Matrix



0   1  2
0  11   0  0
1   0  12  1
2   0   0  6

### Recall, Precision, F1-Score

In [21]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [22]:
print("For Logistic Regression Model")
print("-"*30)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*30)
print("Precision:",precision_score(y_test,y_pred1))
print("Recall:",recall_score(y_test,y_pred1))
print("F1 score:",f1_score(y_test,y_pred1))

For Logistic Regression Model
------------------------------
    0   1
0  26   6
1   0  29
------------------------------
Precision: 0.8285714285714286
Recall: 1.0
F1 score: 0.90625


In [23]:
print("For Decision Tree Model")
print("-"*25)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*25)
print("Precision:",precision_score(y_test,y_pred2))
print("Recall:",recall_score(y_test,y_pred2))
print("F1 score:",f1_score(y_test,y_pred2))

For Decision Tree Model
-------------------------
    0   1
0  25   7
1   1  28
-------------------------
Precision: 0.8
Recall: 0.9655172413793104
F1 score: 0.8750000000000001


##### In above score calculation, we are calculating for Positive(1) class, but in reality those functions are calculating for both the classes

In [24]:
precision_score(y_test,y_pred1,average=None)

array([1.        , 0.82857143])

In [25]:
precision_score(y_test,y_pred2,average=None)

array([0.96153846, 0.8       ])

In [26]:
recall_score(y_test,y_pred1,average=None)

array([0.8125, 1.    ])

In [27]:
recall_score(y_test,y_pred2,average=None)

array([0.78125   , 0.96551724])

#### Recall, Precision, F1-Score for multi-classification problem

In [3]:
df2 = pd.read_csv('/kaggle/input/mnist-digit-recognizer/train.csv')
df2.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [4]:
df2.shape

(42000, 785)

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df2.iloc[:,1:],df2.iloc[:,0],test_size=0.2,random_state=2)

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [7]:
clf5 = LogisticRegression()
clf6 = DecisionTreeClassifier()

In [8]:
clf5.fit(X_train,y_train)
clf6.fit(X_train,y_train)

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [10]:
y_pred1 = clf5.predict(X_test)
y_pred2 = clf6.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression:",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees:",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression: 0.9145238095238095
Accuracy of Decision Trees: 0.8536904761904762


In [12]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,10)))

Logistic Regression Confusion Matrix



0    1    2    3    4    5    6    7    8    9
0  791    0    1    0    1    9   11    1    6    1
1    0  938    2    4    0    3    0    3   12    0
2    2    9  745   16    9    4   13   13   15    3
3    1    4   19  763    0   36    5    5   20   11
4    2    5    4    0  804    1    7    3    9   21
5    9    3    4   23   10  610   15   10   34   11
6   12    4   12    1    7    8  789    0    5    1
7    3    2   13    6    4    2    0  812    2   29
8   11   12   13   18    1   21    6    6  694   11
9    3    6    2   14   25    4    0   37    7  736

In [13]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,10)))

Decision Tree Confusion Matrix



0    1    2    3    4    5    6    7    8    9
0  760    1    9    3    3   17   10    3   12    3
1    1  897   10   12    9    4    4    7   16    2
2    9   16  672   29   18   12   19   22   24    8
3    5   15   34  688    6   47   13   12   24   20
4    7    6   13    8  738    5   12    7   17   43
5    9    6   11   36    9  581   20   14   23   20
6   11    1   12    6   13   26  754    0   10    6
7    2   10   23   15   10    4    2  782    6   19
8    5   14   31   35   17   35   12    5  617   22
9    9    4    9   15   41   20    5   27   22  682

In [14]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [18]:
precision_score(y_test,y_pred1,average=None)

array([0.94844125, 0.95422177, 0.91411043, 0.90295858, 0.93379791,
       0.8739255 , 0.93262411, 0.91235955, 0.86318408, 0.89320388])

In [19]:
precision_score(y_test,y_pred1,average='macro')

0.9128827064397905

In [15]:
precision_score(y_test,y_pred1,average='weighted')

0.9142150713630827

In [16]:
recall_score(y_test,y_pred1,average='weighted')

0.9145238095238095

In [17]:
f1_score(y_test,y_pred1,average='weighted')

0.9142794994052751

##### To Calculate Recall, Precision, F1-Score using single code

In [20]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.95      0.96      0.96       821
           1       0.95      0.98      0.96       962
           2       0.91      0.90      0.91       829
           3       0.90      0.88      0.89       864
           4       0.93      0.94      0.94       856
           5       0.87      0.84      0.85       729
           6       0.93      0.94      0.94       839
           7       0.91      0.93      0.92       873
           8       0.86      0.88      0.87       793
           9       0.89      0.88      0.89       834

    accuracy                           0.91      8400
   macro avg       0.91      0.91      0.91      8400
weighted avg       0.91      0.91      0.91      8400

